import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <section id="section1" className={styles.section}>
          <h2>section 1</h2>
          <p>section 1 paragraph...</p>
        </section>

        <section id="section2" className={styles.section}>
          <h2>section 2</h2>
          <p>section 2 paragraph...</p>
        </section>

        <section id="section3" className={styles.section}>
          <h2>section 3</h2>
          <p>section 3 paragraph...</p>
        </section>

        <section id="section4" className={styles.section}>
          <h2>section 4</h2>
          <p>section 4 paragraph...</p>
        </section>

        <section id="section5" className={styles.section}>
          <h2>section 5</h2>
          <p>section 5 paragraph...</p>
        </section>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <nav className={styles.nav}>
          <Link href="/another">TOP</Link>
          <Link href="#section1">section 1</Link>
          <Link href="#section2">section 2</Link>
          <Link href="#section3">section 3</Link>
          <Link href="#section4">section 4</Link>
          <Link href="#section5">section 5</Link>
        </nav>
      </footer>
    </div>
  );
};

export default Home;
